  sqs-management-api:
    package:
      individually: true  
      include:
        - sqs-api/**
    handler: index.handler
    description: 'Api for management of sqs queues'
    events:
      - http: 'GET /list-sqs-queues'
      - http: 'POST /send-sqs-message'
      - http: 'POST /purge-sqs-queue'
      - http: 'POST /get-messages-from-sqs-queue'