service: serverless-management-api
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
package:
  individually: true
  exclude:
    - ./**
functions:
  - ${file(ec2-api/serverless.yml)}
  - ${file(github-api/serverless.yml)}
  - ${file(lambda-api/serverless.yml)}
  - ${file(sqs-api/serverless.yml)}

