  github-management-api:
    package:
      individually: true  
      include:
        - github-api/**
    handler: github-api/index.handler
    description: 'Api for management for Github'
    events:
      - http: 'ANY /listrepos/{searchforuser}'
      - http: 'ANY /listcommits/{searchforuser}/{githubRepo}'
      