service: github-api
package:
  individually: true
  exclude:
    - "**/*"
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
functions:  
  github-api:
    handler: lib/index.handler
    package:
      include:
        - lib/index.js
        - node_modules/**
        - package.json
        - package-lock.json
    description: 'Api for management for Github'
    events:
      - http:
          path: listrepos/{searchforuser}
          method: ANY
          request:
            parameters:
              paths:
                searchforuser: true
      - http:
          path: listcommits/{searchforuser}/{githubRepo}
          method: ANY
          request:
            parameters:
              paths:
                searchforuser: true
                githubRepo: true
