  ec2-management-api:
    package:
      individually: true  
      include:
        - ec2-api/**
    handler: index.handler
    description: 'Api for management of Ec2 instances'
    events:
      - http: 'GET /list-ec2-instances'
      - http: 'POST /start-ec2-instances'
      - http: 'POST /stop-ec2-instances'