service: serverless-management-for-ec2-api

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  ec2-management-api:
    handler: index.handler
    description: 'Api for management of Ec2 instances'
    events:
      - http: 'GET /list-ec2-instances'
      - http: 'POST /start-ec2-instances'
      - http: 'POST /stop-ec2-instances'