var response = {
    ref: 'refs/heads/master',
    before: 'da5370126735ffe1b73358597eb2e64a1f637774',
    after: '6df6869aad4a263f2ca1210a14eed16bea89e24c',
    created: false,
    deleted: false,
    forced: false,
    base_ref: null,
    compare: 'https://github.com/josephpaulmckenzie/project-manager/compare/da5370126735...6df6869aad4a',
    commits: [{
        id: '6df6869aad4a263f2ca1210a14eed16bea89e24c',
        tree_id: 'e85865f9dbb4a1738aad3581ecdd0db87f82d821',
        distinct: true,
        message: 'got back all pusher/commiter and parsed through info working on repo owner now',
        timestamp: '2019-04-16T19:32:17-04:00',
        url: 'https://github.com/josephpaulmckenzie/project-manager/commit/6df6869aad4a263f2ca1210a14eed16bea89e24c',
        author: [Object],
        committer: [Object],
        added: [],
        removed: [],
        modified: [Array]
    }],
    head_commit: {
        id: '6df6869aad4a263f2ca1210a14eed16bea89e24c',
        tree_id: 'e85865f9dbb4a1738aad3581ecdd0db87f82d821',
        distinct: true,
        message: 'got back all pusher/commiter and parsed through info working on repo owner now',
        timestamp: '2019-04-16T19:32:17-04:00',
        url: 'https://github.com/josephpaulmckenzie/project-manager/commit/6df6869aad4a263f2ca1210a14eed16bea89e24c',
        author: {
            name: 'Joseph Mckenzi',
            email: 'josephmckenzieaz@yahoo.com',
            username: 'josephpaulmckenzie'
        },
        committer: {
            name: 'Joseph Mckenzi',
            email: 'josephmckenzieaz@yahoo.com',
            username: 'josephpaulmckenzie'
        },
        added: [],
        removed: [],
        modified: ['app/src/main/java/com/aws_management/josephmckenzie/project_manager/Aws.java']
    },
    repository: {
        id: 173202139,
        node_id: 'MDEwOlJlcG9zaXRvcnkxNzMyMDIxMzk=',
        name: 'project-manager',
        full_name: 'josephpaulmckenzie/project-manager',
        private: true,
        owner: {
            name: 'josephpaulmckenzie',
            email: 'josephmckenzieaz@yahoo.com',
            login: 'josephpaulmckenzie',
            id: 13924793,
            node_id: 'MDQ6VXNlcjEzOTI0Nzkz',
            avatar_url: 'https://avatars2.githubusercontent.com/u/13924793?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/josephpaulmckenzie',
            html_url: 'https://github.com/josephpaulmckenzie',
            followers_url: 'https://api.github.com/users/josephpaulmckenzie/followers',
            following_url: 'https://api.github.com/users/josephpaulmckenzie/following{/other_user}',
            gists_url: 'https://api.github.com/users/josephpaulmckenzie/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/josephpaulmckenzie/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/josephpaulmckenzie/subscriptions',
            organizations_url: 'https://api.github.com/users/josephpaulmckenzie/orgs',
            repos_url: 'https://api.github.com/users/josephpaulmckenzie/repos',
            events_url: 'https://api.github.com/users/josephpaulmckenzie/events{/privacy}',
            received_events_url: 'https://api.github.com/users/josephpaulmckenzie/received_events',
            type: 'User',
            site_admin: false
        },
        html_url: 'https://github.com/josephpaulmckenzie/project-manager',
        description: null,
        fork: false,
        url: 'https://github.com/josephpaulmckenzie/project-manager',
        forks_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/forks',
        keys_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/keys{/key_id}',
        collaborators_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/teams',
        hooks_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/hooks',
        issue_events_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/issues/events{/number}',
        events_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/events',
        assignees_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/assignees{/user}',
        branches_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/branches{/branch}',
        tags_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/tags',
        blobs_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/languages',
        stargazers_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/stargazers',
        contributors_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/contributors',
        subscribers_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/subscribers',
        subscription_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/subscription',
        commits_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/comments{/number}',
        issue_comment_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/contents/{+path}',
        compare_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/merges',
        archive_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/downloads',
        issues_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/issues{/number}',
        pulls_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/milestones{/number}',
        notifications_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/labels{/name}',
        releases_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/releases{/id}',
        deployments_url: 'https://api.github.com/repos/josephpaulmckenzie/project-manager/deployments',
        created_at: 1551395939,
        updated_at: '2019-04-16T23:29:30Z',
        pushed_at: 1555457541,
        git_url: 'git://github.com/josephpaulmckenzie/project-manager.git',
        ssh_url: 'git@github.com:josephpaulmckenzie/project-manager.git',
        clone_url: 'https://github.com/josephpaulmckenzie/project-manager.git',
        svn_url: 'https://github.com/josephpaulmckenzie/project-manager',
        homepage: null,
        size: 573,
        stargazers_count: 0,
        watchers_count: 0,
        language: 'Java',
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        forks_count: 0,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 0,
        license: null,
        forks: 0,
        open_issues: 0,
        watchers: 0,
        default_branch: 'master',
        stargazers: 0,
        master_branch: 'master'
    },
    pusher: {
        name: 'josephpaulmckenzie',
        email: 'josephmckenzieaz@yahoo.com'
    },
    sender: {
        login: 'josephpaulmckenzie',
        id: 13924793,
        node_id: 'MDQ6VXNlcjEzOTI0Nzkz',
        avatar_url: 'https://avatars2.githubusercontent.com/u/13924793?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/josephpaulmckenzie',
        html_url: 'https://github.com/josephpaulmckenzie',
        followers_url: 'https://api.github.com/users/josephpaulmckenzie/followers',
        following_url: 'https://api.github.com/users/josephpaulmckenzie/following{/other_user}',
        gists_url: 'https://api.github.com/users/josephpaulmckenzie/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/josephpaulmckenzie/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/josephpaulmckenzie/subscriptions',
        organizations_url: 'https://api.github.com/users/josephpaulmckenzie/orgs',
        repos_url: 'https://api.github.com/users/josephpaulmckenzie/repos',
        events_url: 'https://api.github.com/users/josephpaulmckenzie/events{/privacy}',
        received_events_url: 'https://api.github.com/users/josephpaulmckenzie/received_events',
        type: 'User',
        site_admin: false
    }
};

// console.log("response",response)

var wholething = response;

console.log(wholething.commits[0].committer)
// var name = commits.committer.name;
// email = JSON.parse(email)
// var commitMessage = commits.message; 
// var timestamp = commits.timestamp; 



// console.log(name,username,email,commitMessage,timestamp)